### ISSUE TITLE
What is the microcontroller in the picture?

### ISSUE THREAD

**Issue by Billzabob** [MangoIV/dracuLad#4]
The microcontroller in this image has an awesome design! What is it? Or if that's just a cover of some sort, where can I get one?

![](https://raw.githubusercontent.com/mangoiv/draculad/master/pictures/rev2/fr4_glamour3.jpeg)

**Comment by floookay** [comment]
That's a Puchi-C. I got one from keycapsss.com a few months ago but they're out of stock right now.  
Great controller, also slightly cheaper than an Elite-C or Bit-C.
