### ISSUE TITLE
Where may I find the keymap for pimoroni?

### ISSUE THREAD

**Issue by kojameslau** [MangoIV/dracuLad#5]
The build guide mentioned: 'for the pimoronis you should not compile the default keymap but rather the "pimoroni" one' but I only see one for DracuLad in QMK Toolbox.

**Comment by MangoIV** [comment]
Hi! This is for compiling with the qmk toolchain. I do not know whether you can find it in the toolbox as I don't use that myself. 
If you want to use the pimoroni it's probably a good idea to make a proper QMK-Setup anyways. 
For flashing the standard pimoroni keymap you just have to run 
`qmk flash -kb draculad -km pimoroni -bl <your-bootloader>`
or directly with `make`
`make draculad:pimoroni:flash` or `:dfu` depending on your bootloader.
