### ISSUE TITLE
total newbe help'on how to build the gerber

### ISSUE THREAD

**Issue by lpanebr** [MangoIV/dracuLad#8]
hi, I love this layout but I don't know which of the pcb files I need to open in kicad to create the gerber file.

any tips???

thanks!

**Comment by MangoIV** [comment]
The `.pro` files are the kicad project files :)

**Comment by lpanebr** [comment]
thanks! I later noticed that the gerbers.zip was already there.
I found a yt video that helped and already placed the order.
